title: Pavel Khrulev
description: > # this means to ignore newlines until "baseurl:"
  I'm a Solution Architect. Specialize in Clouds and DevOps architecture. This
  site is made to host my blog posts and various content I'd like to share
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://khrulev.me" #"http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
#site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Pavel Khrulev # add your name
author-img: pavel-khrulev.jpeg # add your photo
about-author: I'm a Solution Architect. Specialize in Clouds and DevOps architecture. This site is made to host my blog posts and various content I'd like to share
#social-twitter: # add your Twitter handle
#social-facebook: # add your Facebook handle
social-github: pkhrulev
social-linkedin: pavel-khrulev-06420367 # add your Linkedin handle
social-email: pavel.khrulev@gmail.com # add your Email address

# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
#analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
